### ISSUE TITLE
check that your file system ID is correct, and ensure that the VPC has an EFS mount target for this file system ID

### ISSUE THREAD

**Issue by ericrobertn** [ydamni/cloud-is-free#3]
Hey Team, 

Hoping posting an issue here is ok. I can't seem to get past step 7 in project-3. I've deleted and re-created my EFS. Checked my Security rules. Everything seems to be in place. I've got an imgur link to my settings and a paste from the output of the error. Let me know if I can provide anything else. 

Some possible reasons I saw on other threads is the containers are using different DNS but I haven't manually set anything so it should all be default. 

https://imgur.com/a/SXpEkN0

Error response from daemon: create ecs-td-metabase-6-metabase-volume-9eb7f486c9c6ae8d4600: VolumeDriver.Create: mounting volume failed: Failed to resolve "fs-02417eff7308d5026.efs.ap-northeast-1.amazonaws.com" - check that your file system ID is correct, and ensure that the VPC has an EFS mount target for this file system ID. See https://docs.aws.amazon.com/console/efs/mount-dns-name for more detail. Attempting to lookup mount target ip address using botocore. Failed to import necessary dependency botocore, please install botocore first.

**Comment by ydamni** [comment]
In view of the error message, and after analyzing the screenshots, I am sure that the problem is due to the fact that DNS hostnames have not been activated on the VPC when created.

To fix this problem, follow the steps on the screens below:

https://imgur.com/a/vxs7Xbv

By doing this:
- The EC2 instance will have a public hostname (convenient but not important);
- the EFS volume will have a public hostname (PRIMORDIAL to link the EFS volume to ECS containers).

And by the way, be sure that the EFS volume is linked to the correct VPC and AZ! If you followed the step 7 correctly, this should have been done.

Please let me know if this fixed the problem.
Good luck with the rest of the project!

**Comment by ericrobertn** [comment]
It looks like I had a few things wrong but you've pointed me in the right direction. As you guessed the DNS hostnames were disabled. I was also building the EFS in ap-northeast-1a when my EC2 Instance was in 1a. It's still failing but now I know where to look. Thanks for the help! This has given me some great insight into how AWS works.
